<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>MudBlazorWebApp1-Development</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\BraSeller.Connectors.Abstractions\BraSeller.Connectors.Abstractions.csproj" />
    <ProjectReference Include="..\MudBlazorWebApp1.Client\MudBlazorWebApp1.Client.csproj"
                      AdditionalProperties="PublishReadyToRun=false"
                      GlobalPropertiesToRemove="PublishProfile;PublishReadyToRun" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.*" />
    <PackageReference Include="ClosedXML" Version="0.105.*" />
    <PackageReference Include="QuestPDF" Version="2026.*" />
    <PackageReference Include="MailKit" Version="4.*" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.414.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\BraSeller.Connector.MercadoLivre\MercadoLivreConnector.cs" Link="Connectors\MercadoLivre\MercadoLivreConnector.cs" />
    <Compile Include="..\BraSeller.Connector.MercadoLivre\MercadoLivreModule.cs" Link="Connectors\MercadoLivre\MercadoLivreModule.cs" />
    <Compile Include="..\BraSeller.Connector.MercadoLivre\MercadoLivreOptions.cs" Link="Connectors\MercadoLivre\MercadoLivreOptions.cs" />
    <Compile Include="..\BraSeller.Connector.MercadoLivre\MercadoLivreRateLimiter.cs" Link="Connectors\MercadoLivre\MercadoLivreRateLimiter.cs" />
  </ItemGroup>

</Project>
