using System.Text.Json.Serialization;

namespace Avallo.Web.Infrastructure;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
[JsonSerializable(typeof(Features.Auth.RegisterRequest))]
[JsonSerializable(typeof(Features.Auth.LoginRequest))]
[JsonSerializable(typeof(Features.Auth.CreateTenantUserRequest))]
[JsonSerializable(typeof(Features.Auth.UpdateProfileRequest))]
[JsonSerializable(typeof(Features.Auth.ChangePasswordRequest))]
[JsonSerializable(typeof(Features.Auth.UpdateTenantUserStatusRequest))]
[JsonSerializable(typeof(Features.Auth.TokenResponse))]
[JsonSerializable(typeof(Features.Auth.UserResponse))]
[JsonSerializable(typeof(Features.Auth.TenantUserResponse[]))]
[JsonSerializable(typeof(Features.Reports.DashboardReport))]
[JsonSerializable(typeof(Features.Reports.PagedEntries))]
[JsonSerializable(typeof(Features.Reports.ReportOptions))]
[JsonSerializable(typeof(Features.Notifications.NotificationListResponse))]
[JsonSerializable(typeof(Features.Notifications.NotificationPreferenceResponse))]
[JsonSerializable(typeof(Features.Notifications.UpdateNotificationPreferenceRequest))]
[JsonSerializable(typeof(Features.Connectors.AuthenticateConnectorRequest))]
[JsonSerializable(typeof(Features.Connectors.SyncConnectorRequest))]
[JsonSerializable(typeof(Features.Connectors.ConnectionResponse[]))]
[JsonSerializable(typeof(Features.Connectors.SyncResult))]
[JsonSerializable(typeof(Avallo.Connectors.Abstractions.ConnectorDescriptor[]))]
[JsonSerializable(typeof(Avallo.Connectors.Abstractions.StandardOrder))]
[JsonSerializable(typeof(Avallo.Connectors.Abstractions.StandardPayment[]))]
[JsonSerializable(typeof(Avallo.Connectors.Abstractions.StandardFee[]))]
[JsonSerializable(typeof(Avallo.Connectors.Abstractions.StandardInvoice[]))]
[JsonSerializable(typeof(Avallo.Connectors.Abstractions.ConnectorStatus))]
[JsonSerializable(typeof(Features.Accounting.PreliminaryDre))]
[JsonSerializable(typeof(Features.Expenses.ExpenseRequest))]
[JsonSerializable(typeof(Features.Expenses.RejectExpenseRequest))]
[JsonSerializable(typeof(Features.Expenses.ExpenseResponse[]))]
[JsonSerializable(typeof(Features.Expenses.ExpenseAttachmentResponse))]
[JsonSerializable(typeof(Features.Expenses.AttachmentDownloadResponse))]
[JsonSerializable(typeof(Features.Inventory.InventoryOverviewResponse))]
[JsonSerializable(typeof(Features.Inventory.CreateSkuMappingRequest))]
[JsonSerializable(typeof(Features.Inventory.SkuMappingResponse))]
[JsonSerializable(typeof(Features.Inventory.ReprocessInventoryResponse))]
[JsonSerializable(typeof(Features.Fiscal.FiscalOverviewResponse))]
[JsonSerializable(typeof(Features.Fiscal.CnpjLookupResponse))]
[JsonSerializable(typeof(Features.Fiscal.BrasilApiCnpjResult))]
[JsonSerializable(typeof(Features.Fiscal.BrasilApiCnae))]
[JsonSerializable(typeof(Features.Fiscal.BrasilApiTaxRegime))]
[JsonSerializable(typeof(Features.Fiscal.CnpjWsResponse))]
[JsonSerializable(typeof(Features.Fiscal.CreateTaxProfileRequest))]
[JsonSerializable(typeof(Features.Fiscal.TaxProfileResponse))]
[JsonSerializable(typeof(Features.Fiscal.CreateTaxRuleRequest))]
[JsonSerializable(typeof(Features.Fiscal.ReviewTaxRuleRequest))]
[JsonSerializable(typeof(Features.Fiscal.TaxRuleResponse))]
[JsonSerializable(typeof(Features.Fiscal.TaxSimulationRequest))]
[JsonSerializable(typeof(Features.Fiscal.TaxSimulationResponse))]
[JsonSerializable(typeof(Features.Fiscal.ReprocessTaxResponse))]
[JsonSerializable(typeof(Features.PeriodClosing.AccountingPeriodResponse[]))]
[JsonSerializable(typeof(Features.PeriodClosing.PeriodValidationResponse))]
[JsonSerializable(typeof(Features.PeriodClosing.ReopenPeriodRequest))]
[JsonSerializable(typeof(Features.PeriodClosing.SnapshotDownloadResponse))]
[JsonSerializable(typeof(Features.Reconciliation.ReconciliationOverviewResponse))]
[JsonSerializable(typeof(Features.Reconciliation.ReconciliationImportResponse))]
[JsonSerializable(typeof(Features.Reconciliation.ConfirmReconciliationRequest))]
[JsonSerializable(typeof(Features.Reconciliation.IgnoreReconciliationRequest))]
[JsonSerializable(typeof(Features.Reconciliation.ReconciliationActionResponse))]
public partial class AppJsonSerializerContext : JsonSerializerContext;
